### Creates new entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Banjo timmy2",
  "address": "46, carlow strret, middlesbrough",
  "email": "timmybanjo2@gmail.com",
  "dateOfBirth": "1999-12-29",
  "registeredDate": "2026-11-01"
}
###